services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: api:latest  # Добавляем имя образа
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin_pg:supersecret@database:5432/tacacs_db
    networks:
      - tac_network

networks:
  tac_network:
    external: true
    name: docker_tac_network
